### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by candidobugarin** [antarcticrainforest/tint4all#1]
Hello! First I would like to congratulate you for the excellent work! I'm from Brazil and I work with weather radar data and I was very excited to test your application. I would like to ask a question:

Can I do some sort of processing for the clusters before running your application or is this already done in the application? I ask you this question because I was thinking about doing the DBSCAN processing and entering the data into your algorithm.

Currently I open the radar files with Py-ART and my idea was to put this data inside your algorithm to perform some tests.

Thank you!

**Comment by antarcticrainforest** [comment]
Hi @candidobugarin,
sorry for not getting back to you earlier. I must have missed the notification email. In fact this repository is based on a fork of this repository (https://github.com/openradar/TINT). It uses natively Py-ART so naturally this would be your repo of choice. A created this repository for people how want to use model output data which is not compatible with Py-ART. 

To answer your question: you could use TINT together with ipyparallel or some of the following repositories that handle HPC scheduling:

https://github.com/pharmbio/sciluigi
https://github.com/garstka/idact
https://github.com/luptior/pysbatch
https://github.com/basnijholt/hpc05
https://github.com/roryk/ipython-cluster-helper

Yet your suggestion is an interesting one, so I'll try to add some HPC functionality.

**Comment by antarcticrainforest** [comment]
Sorry I just realized I messed up your question. I was thinking that you wanted to submit track jobs to a computing cluster. Silly me.

To answer your real qeustion: No there is no sort of pre-processing involved. I can imagine adding generator that yields from a user defined processing method. This would make pre-processing quite simple.

**Comment by antarcticrainforest** [comment]
Sorry again for the late response. I am not sure whether or not this is still helpful.
